### ISSUE TITLE
spacemacs没能load

### ISSUE THREAD

**Issue by ziyuanjun** [thiefuniverse/blog-minimal#2]
我用的是spacemacs，在`defun dotspacemacs/user-config ()`中写：
```
 (add-to-list 'load-path "~/Program/Blog/blog-minimal")
```
但是重启并没有自动load。
我手动`load-file` blog-minimal下面的blog-minimal.el、bm-utils.el 、bm-vars.el三个.el文件是可以的。不知道这样是不是影响使用？

**Comment by thiefuniverse** [comment]
你可以把这个添加到你的 _dotspacemacs/user-config ()_ 函数里试一试
```elisp
     (use-package blog-minimal
       :load-path "~/Program/Blog/blog-minimal"
      )

```
我觉得可能和spacemacs的加载顺序有关系，可能user-config是在加载完package之后才执行.

**Comment by ziyuanjun** [comment]
这样做可以自动加载了

**Comment by thiefuniverse** [comment]
这样实际上就是手动加载了,看了下spacemacs的本地包加载，不是很懂，好像要和层相关联，这样应该也可以；
已经pull requests到melpa了，能通过就方便点了 :laughing: 
希望可以多提建议，共同维护!

**Comment by ziyuanjun** [comment]
我前端的知识有些薄弱，学习中

**Comment by thiefuniverse** [comment]
恩，共同交流！
