### ISSUE TITLE
bm/init，bm/render**出错

### ISSUE THREAD

**Issue by ziyuanjun** [thiefuniverse/blog-minimal#3]
调用bm/init, bm/render-all-org-files, bm/render-current-article都会报这个错误：

`progn: Read error: 是一个目录, /home/ziyuan/Program/Blog/test/org/templates`

PS: 我在就clone后改了`bm/blog-main-dir`： "/home/ziyuan/Program/Blog/test/"，并把templates文件夹复制到了该目录下。另外，我是第一次装上mustache、simple-httpd是不是这两个package需要做什么配置呢？

**Comment by thiefuniverse** [comment]
templates目录应该是和org目录同级的,你不用手动复制templates过来
org目录下面应该都是org文件

**Comment by thiefuniverse** [comment]
mustache和simple-htttpd只要装上就行了,不用配置.

**Comment by ziyuanjun** [comment]
我重新试了一下，如果当前buffer是org文件，那么bm/render-current-article还是会报错，但render-all-org-files是可以的。

**Comment by thiefuniverse** [comment]
图片你可以自己建一个目录,如果是github pages的话在插入图片的时候把位置构造好就行了
这个可以功能可以添加
