### ISSUE TITLE
blog-minimal-init compilation error: Symbol's function definition is void: org-make-options-regexp

### ISSUE THREAD

**Issue by ZenStudioLab** [thiefuniverse/blog-minimal#6]
Hi,
This bug is solved on my machine *Fedora 25* - *Emacs 25.1.1* by adding 

`;; importing org mode`
`(require 'org)`

unto the file *blog-minimal-utils.el*

I am not quite sure this is a local problem within my machine or universally.
Toan.

**Comment by thiefuniverse** [comment]
Yes, I use ox-html which belongs to org. I have added **(require 'org)**.  Thanks.

**Comment by thiefuniverse** [comment]
Add dependency .
